### PR TITLE
remove autogenerated files from repo

### PR DESCRIPTION
**Pull request by adammoody**

### CODE REVIEW

**Comment by adammoody** [comment]
To complete this, we'd want "make dist" to work so that we can build and post a release tarball.

**Comment by adammoody** [comment]
make dist should work now

**Comment by adammoody** [comment]
Should probably pull this before https://github.com/LLNL/libyogrt/pull/3

**Comment by morrone** [comment]
I took this, reworked it a bit, added some things, and landed it in PR #5.

**Pull request closed without merging**
