### PR TITLE
LSF

### PR DESCRIPTION
**Pull request by adammoody**
Adds support to get time remaining for LSF jobs.

### CODE REVIEW

**Comment by adammoody** [comment]
This is a work in progress.

**Comment by lipari** [comment]
@adammoody, What I see so far looks good.  Once you have finished your last edit, I suggest you squash all of the commits down to one.  Just my opinion.  However given that @morrone was the originator of this library, I defer to his judgement.  I also leave it to him to merge when he has had a chance to review and comment.

**Comment by adammoody** [comment]
@lipari Sure, good idea.  I can squash them.  I'll wait a bit to do that since more commits may be coming before that.

One other thing I noticed is that the repo is tracking the autogenerated files like Makefile.in.  I haven't checked these in yet.  Not sure if I should do that or whether we'd rather drop those from being tracked in git.

**Comment by lipari** [comment]
>  Not sure if I should do that or whether we'd rather drop those from being tracked in git.

Deferring to @morrone

**Comment by adammoody** [comment]
Ok, ready for review on this

**Comment by morrone** [comment]
I rebased your commit and made some minor changes to make it match the autotools updates that I made elsewhere.  I'm landing it.  It would be good for you to check and make sure I didn't break anything. :)

**Comment by adammoody** [comment]
Tested the LSF code again, and it's all still working.  Thanks for reviewing and merging this.

Can we tick the version number and post a tarball?  I don't mind doing that, but I don't seem to have write access to the repo.

**Pull request merged**
